# Generated by Django 5.1.2 on 2024-11-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pies',
            name='users',
        ),
        migrations.AddField(
            model_name='pies',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pies', to='app.user'),
            preserve_default=False,
        ),
    ]
