# Generated by Django 5.1.2 on 2024-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('network', models.CharField(max_length=10)),
                ('released_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
