# Generated by Django 5.1.2 on 2024-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
